### PR TITLE
Update astropy-helpers to v2.0

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v2.0. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by weaverba137** [comment]
> This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!

@bsipocz, @astrofrog, I noticed some issues with this automated update!

In particular, tests against `ASTROPY_VERSION=development` seem to be erroring out, not just failing.

**Comment by bsipocz** [comment]
@weaverba137 - The failure is unrelated to this PR, and I suspect ``pydl`` master is incompatible with astropy 2.0. The tests here were still using 1.3.3.

One way to spot these earlier is to use the cron feature of travis and report possible issues upstream while they are still in dev or RC testing.

cc @adrn @eteq

**Comment by adrn** [comment]
The build failure is the same issue as was raised at the bottom of #6300. This is fixed in #6357 and should be in the first bugfix release.

The core problem is that the `*FrameAttribute` classes were renamed to be just `Attribute`, so wherever you have `from astropy.coordinates import FrameAttribute` you'll instead want `from astropy.coordinates import Attribute` (and change other code accordingly).

**Comment by weaverba137** [comment]
@adrn, just to be clear, this problem only exists in `ASTROPY_VERSION=development`, correct?

Also, since I understand that Astropy v3.0 will not support Python 2, does it make sense to test the combination `PYTHON_VERSION=2.7 ASTROPY_VERSION=development` at all?

**Comment by bsipocz** [comment]
@weaverba137 - If you restart the travis builds, it will affect all jobs that is against "latest" or "development" as this PR was opened before the "latest" tag got updated in ci-helpers to point to the 2.0 release. 
However the dev build are expected to pass again once the PR @adrn mentions get merged.  

You're right that testing dev and python2 won't make much sense once we remove the python2 support.

**Comment by weaverba137** [comment]
I'm closing this in favor of #30.

**Pull request closed without merging**
