### PR TITLE
Update astropy-helpers to v2.0.2

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by weaverba137** [comment]
Travis still thinks this PR is onto master, so I'm going to close this & update on my own branch.

**Comment by bsipocz** [comment]
This was supposed to be on master, wasn't it?

**Comment by weaverba137** [comment]
The *automation* was supposed to be on master, but the upgrade broke something to do with Sphinx builds, and in addition the .travis.yml file needed to be upgraded.  So have to revert to manual.

**Comment by bsipocz** [comment]
I see. Actually as a maintainer you can directly push commits to any branches of forks that have opened PRs from them.

**Comment by weaverba137** [comment]
If there's a document I can cut-and-paste the commands from, then I'll consider doing that next time.

**Comment by bsipocz** [comment]
https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

**Pull request closed without merging**
